### ISSUE TITLE
Provide documentation on how to create map package

### ISSUE THREAD

**Issue by zeridon** [c3nav/c3nav#14]
We are planning to experiment with c3nav for Openfest 2017. The one missing thing is that there is no documentation how to create the map packages and how are they structured.

Please provide at least a barebone documentation how this is supposed to happen.

**Comment by nomoketo** [comment]
c3nav is currently in no state to be used, currently i'm working on getting the next stable version out until september. I'm not going to support or add any documentation for the old 33c3 version of c3nav any more, sorry =(

**Comment by zeridon** [comment]
Then where can i get the new version (even if dev). The event is in early november so we really want to try out few things before we settle on a tool.

**Comment by nomoketo** [comment]
The new version is the current master branch. It is currently undergoing heavy refactoring and only the Map Editor works. The docs still reflect the old 33c3 version. Sorry, i really can't offer any support at the moment for either the new nor the old version.

c3nav will be set up for an event in early september, then you'll be able to see more.
The old version of c3nav was last set up from the people organizing FOSDEM. Maybe they can help you. Please keep in mind though that migrating to the new version (keeping map data), while definitely possible, is currently not a priority because c3nav was only used for two events so far.
