### ISSUE TITLE
entrance east missing

### ISSUE THREAD

**Issue by izumariu** [c3nav/c3nav#40]
Hi guys,

you forgot the entrance on the east in the 35c3 c3nav.

![grafik](https://user-images.githubusercontent.com/16462014/71313902-31c93c00-2440-11ea-975c-a9749d335bc9.png)

**Comment by codingcatgirl** [comment]
Wow, thanks! 2 years we're there already and we never noticed that this integral area is missing!

…or maybe, just maybe, it's intentional because that building is not part of the Chaos Communication Congress. Have you been there once?

FYI, there's also a big part of the Messehaus missing, because the congress isn't happening there.

**Comment by codingcatgirl** [comment]
Wow, thanks! 2 years we're there already and we never noticed that this integral area is missing!

…or maybe, just maybe, it's intentional because that building is not part of the Chaos Communication Congress. ;) Have you been there once?

----

FYI, there's also a big part of the Messehaus missing, because the congress isn't happening there either…yet.

![U0OQ0HWC](https://user-images.githubusercontent.com/3868507/71316470-3a396b00-2470-11ea-8b35-198ec19b9174.jpg)

**Comment by izumariu** [comment]
I mean, you could use that small eastern entrace to reach hall 5 from hall 4 pretty quickly, that's why I think it should be included.

**Comment by codingcatgirl** [comment]
Are you being serious right now? Is this a joke? We are the c3nav, just because we put something on the map, doesn't mean it suddenly becomes part of the congress, that's not how it works. If you want the East Entrance to become part of the Congress, talk to the Congress Orga, not us. You realize that booking an additional area from the Messe Leipzig will also cost money, right?

Also, again, have you been to the congress in Leipzig, ever? Hall 4 is the LOC. That's a backstage area, you can't even get there if you aren't an angel. So it wouldn't even be big of an advantage is the east entrance *was* open.

I'm trying to wrap my head around what you're trying to achieve here, because it really feels so incredibly pointless. I can't believe i'm saying this, but… please just accept that c3nav is showing you the congress, not what you think should be the congress. Thank you.

Unless the eastern entrance is starting to be publicly accessibly for congress attendees this year, we have nothing to talk about.
